### PR TITLE
Replace mount by xorriso

### PR DESCRIPTION
**Pull request by maniackcrudelis**
Because that fucking lxd doesn't want to allow to mount an iso...

### CODE REVIEW

**Review by zamentur — COMMENTED** [review]
Do you think it waoks with dd now (because you use xoriso) ?

**Comment by maniackcrudelis** [comment]
I don't know, I never used dd with an iso.

**Comment by alexAubin** [comment]
Further investigating this, I found these pages : 

https://askubuntu.com/questions/625286/how-to-create-uefi-bootable-iso
http://www.syslinux.org/wiki/index.php?title=Isohybrid

In particular, this summarize the issue : 
>ISO 9660 filesystems created by the mkisofs command as described in the ISOLINUX article will boot via BIOS firmware, but only from optical media like CD, DVD, or BD.
>The isohybrid feature enhances such filesystems by a Master Boot Record (MBR) for booting via BIOS from disk storage devices like USB flash drives. 

I'll investigate the `-isohybrid-mbr` option of xorriso that should solve this issue.

**Comment by alexAubin** [comment]
Yolomerging because current status is already good. Working on dd/Etcher compatibility will be an improvement but can be thinked as outside the scope of this PR ;)

**Pull request merged**
